### ISSUE TITLE
需要支持高DPI缩放

### ISSUE THREAD

**Issue by XingKongYeMing** [PaC-Software/NEO-MsgBox#2]
需要支持高DPI缩放
注：以下现象都是在2k显示器下的情况
若使用150%或更高的dpi缩放替代，那么程序将会显示模糊。
若在兼容性设置中禁用系统显示缩放，则窗口会变得极小。

**Comment by LAGQWQ** [comment]
感谢你的反馈，由于易语言特性，DPI缩放需要**更改存根**。我们可能会在`0.2`版本加入你的`feat`!
